name: Gradle CI

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Cache gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Cache conduit dev
      uses: actions/cache@v1
      with:
        path: ConduitLauncher/
        key: ${{ runner.os }}-ConduitLauncher

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Conduit dev
      run: mkdir -p ConduitLauncher && wget http://repo.conduit.systems/repository/releases/systems/conduit/ConduitLauncher/1.0.0/ConduitLauncher-1.0.0.jar -O ./ConduitLauncher/ConduitLauncher.jar

    - name: Run Conduit dev
      run: cd ConduitLauncher && java -jar ConduitLauncher.jar dev && cd ..

    - name: Build with gradle
      run: ./gradlew build

    - name: Publish with gradle
      if: success() && github.ref == 'refs/heads/master'
      run: ./gradlew publish -DMAVEN_PASSWORD=${{ secrets.MAVEN_PASSWORD }}
