name: Gradle CI

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Cache gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache build cache
      uses: actions/cache@v1
      with:
        path: build/cache
        key: ${{ runner.os }}-build-cache-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-build-cache-

    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '16'

    - name: Build Conduit
      run: ./gradlew build

    - name: Publish Conduit
      if: success() && github.ref == 'refs/heads/master'
      run: ./gradlew publish -DMAVEN_PASSWORD=${{ secrets.MAVEN_PASSWORD }}
